name: My Checkov Demo Workflow version1 

on:
  push:
    branches:
      - master

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Checkov
        #run: curl -L https://github.com/bridgecrewio/checkov/releases/latest/download/checkov-linux-arm64 -o checkov && chmod +x checkov && pwd && which checkov 
        run: pip install -U checkov 
      - name: Run Checkov scan
        run: checkov -d terraform/aws/
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0