name: My Checkov Demo Workflow version2
on:
  push:
    branches:
      - master

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Checkov
        #run: curl -L https://github.com/bridgecrewio/checkov/releases/latest/download/checkov-linux-arm64 -o checkov && chmod +x checkov && pwd && which checkov 
        run: pip install -U checkov 
      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with: 
          soft_fail: true 


        
